// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kagpsmborugjrtuhprzw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImthZ3BzbWJvcnVnanJ0dWhwcnp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MDUzMDUsImV4cCI6MjA2NjE4MTMwNX0.imR6LwUpSdHtv2jWao5KWa8mXmzCOuA4uJ-FxaZUAm8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);